    puts "🌱 Seeding spices..."

# Seed your database here
puts "Deleting User/Game/Watchlist data..."
User.destroy_all
Game.destroy_all
Watchlist.destroy_all

puts "Creating users..."
user1 = User.create(username: "harris")

puts "Creating games..."
game1 = Game.create(title:"Kirby and the Forgotten Land", genre: "Adventure Game", release_date:"March 25, 2022", summary: "In Kirby and the Forgotten Land, the fearless pink puffball finds himself in a strange post-apocalyptic world, where nature has taken over civilization. But in true Kirby fashion, he heeds the call to rescue the Waddle Dees who have been kidnapped by the mysterious Beast Pack.", image:"https://images.nintendolife.com/1ddb829d9a730/kirby-and-the-forgotten-land-cover.cover_large.jpg", platform:"Nintendo Switch", price:59.99)
game2 = Game.create(title:"Fire Emblem Warriors: Three Hopes", genre: "Hack and Slash", release_date:"June 24, 2022", summary: "Fire Emblem Warriors: Three Hopes is an upcoming hack and slash action role-playing game developed by Omega Force and Team Ninja, and published by Nintendo for the Nintendo Switch.", image:"https://upload.wikimedia.org/wikipedia/en/thumb/a/ad/Fire_Emblem_Warriors_Three_Hopes.jpg/220px-Fire_Emblem_Warriors_Three_Hopes.jpg", platform:"Nintendo Switch", price:59.99)
game3 = Game.create(title:"Nintendo Switch Sports", genre: "Sim Game", release_date:"April 29, 2022", summary: "Nintendo Switch Sports is an upcoming sports simulation video game developed and published by Nintendo for the Nintendo Switch. It is the third main entry in the Wii Sports series of games. The game's release is scheduled for April 29, 2022.", image:"https://upload.wikimedia.org/wikipedia/en/thumb/f/f0/Nintendo_Switch_Sports_logo_icon.png/220px-Nintendo_Switch_Sports_logo_icon.png", platform:"Nintendo Switch", price:39.99)
game4 = Game.create(title:"Mario Strikers: Battle League", genre: "Sim Game", release_date:"June 10, 2022", summary: "Mario Strikers: Battle League, known in Europe and Australia as Mario Strikers: Battle League Football, is an upcoming association football/soccer video game developed by Next Level Games and Nintendo EPD and published by Nintendo. It is scheduled for a worldwide release on the Nintendo Switch on June 10, 2022.", image:"https://upload.wikimedia.org/wikipedia/en/thumb/4/4e/Mario_strikers_battle_league.jpeg/220px-Mario_strikers_battle_league.jpeg", platform:"Nintendo Switch", price:59.99)
game5 = Game.create(title:"Chocobo GP", genre: "Racing Game", release_date:"March 10, 2022", summary: "", platform:"Nintendo Switch", image:"", price:59.99)
game6 = Game.create(title:"Monster Hunter Rise", genre: "Action role-playing", release_date: "January 20, 2022", summary: "Monster Hunter Rise is an action role-playing game developed and published by Capcom for the Nintendo Switch. It is the sixth mainline installment in the Monster Hunter series and was released worldwide in March 2021. A Microsoft Windows version was released in January 2022.", platform:"PC", image:"https://upload.wikimedia.org/wikipedia/en/4/41/Monster_hunter_rise_cover.jpg", price:59.99)
game7 = Game.create(title:"Tom Clancy's Rainbow Six Extraction", genre: "Tactical shooter", release_date:"January 20, 2022", summary: "Tom Clancy's Rainbow Six Extraction is an online multiplayer tactical shooter video game developed by Ubisoft Montreal and published by Ubisoft.", platform:"PC", image: "https://upload.wikimedia.org/wikipedia/en/9/98/Rainbow_Six_Extraction_cover_art.jpg", price:39.99)
game8 = Game.create(title:"Vampire: The Masquerade Bloodlines 2", genre: "Action role-playing", release_date:"TBD", summary: "Vampire: The Masquerade Bloodlines 2 is an upcoming action role-playing video game published by Paradox Interactive. A sequel to Vampire: The Masquerade Bloodlines, the game is part of the World of Darkness series and based on the tabletop role-playing game Vampire: The Masquerade.", platform:"PC", image: "https://upload.wikimedia.org/wikipedia/en/9/90/Vampire_The_Masquerade_Bloodlines_2_Cover_Art.png", price:89.99)
game9 = Game.create(title:"System Shock", genre: "Action-adventure", release_date:"TBD", summary: "System Shock is a 1994 first-person action-adventure video game developed by LookingGlass Technologies and published by Origin Systems. It was directed by Doug Church with Warren Spector serving as producer. The game is set aboard a space station in a cyberpunk vision of the year 2072.", platform:"PC", image: "https://upload.wikimedia.org/wikipedia/en/9/93/Sysshock.jpg", price:59.99)
game10 = Game.create(title:"Kerbal Space Program 2", genre: "Space fight simulation", release_date:"TBD", summary: "Kerbal Space Program 2 is an upcoming space flight simulation video game developed by Intercept Games and published by Private Division. It is the sequel to 2015's Kerbal Space Program and is scheduled for release in 2022 for Microsoft Windows, PlayStation 4, PlayStation 5, Xbox One and Xbox Series X/S.", platform:"PC", image: "https://images.gnwcdn.com/2015/articles/1/8/4/2/5/7/9/-1468227306289.jpg/EG11/thumbnail/732x412/formatPC", price:59.99)
game11 = Game.create(title:"Dying Light 2", genre: "Action role-playing", release_date:"February 2, 2022", summary: "Dying Light 2 Stay Human is a 2022 action role-playing game developed and published by Techland. The sequel to Dying Light, the game was released on February 4, 2022 for Microsoft Windows, PlayStation 4, PlayStation 5, Xbox One, and Xbox Series X/S. A Nintendo Switch version for the cloud is currently in development.", platform: "PC", image:"https://upload.wikimedia.org/wikipedia/en/6/6d/Dying_Light_2_cover_art.jpg", price:59.99)
game12 = Game.create(title:"Stalker 2", genre: "First-person shooter", release_date:"December 8, 2022", summary: "S.T.A.L.K.E.R. 2: Heart of Chernobyl is an upcoming first-person shooter survival horror video game developed and published by GSC Game World. Set to release for Microsoft Windows and the Xbox Series X/S in December 2022, it will be the fourth game released in the S.T.A.L.K.E.R.", platform: "PC", image:"https://upload.wikimedia.org/wikipedia/en/8/80/STALKER_2_cover_art.jpg", price:59.99)
game13 = Game.create(title:"Elden Ring", genre: "Action role-playing game", release_date:"February 25, 2022", summary: "Elden Ring is an action role-playing game developed by FromSoftware and published by Bandai Namco Entertainment. The game was made in collaboration with fantasy novelist George R. R. Martin, who provided material for the game's setting.", platform: "PC", image:"https://upload.wikimedia.org/wikipedia/en/b/b9/Elden_Ring_Box_art.jpg", price:59.99)
game14 = Game.create(title:"Warhammer 40,000: Darktide", genre: "Indie game", release_date:"TBD", summary: "Warhammer 40,000: Darktide is an upcoming first-person action game set in the Warhammer 40,000 universe, being developed and published by Swedish video game studio Fatshark.", platform: "PC", image:"https://upload.wikimedia.org/wikipedia/en/6/6f/Darktide_art.jpg", price:59.99)
game15 = Game.create(title:"Tunic", genre: "Indie game", release_date:"March 16, 2022", summary: "Tunic is an upcoming action-adventure game developed by Canadian indie developer Andrew Shouldice and published by Finji.", platform: "PC", image:"https://upload.wikimedia.org/wikipedia/en/4/4b/Tunic_video_game_title.png", price:59.99)
game16 = Game.create(title:"The Settlers", genre: "Real-time strategy", release_date:"March 17, 2022", summary: "The Settlers is a city-building and real-time strategy video game series created by Volker Wertich.", platform: "PC", image:"https://omggamer.com/wp-content/uploads/2021/01/The-Settlers-Release-Date.jpeg", price:59.99)
game17 = Game.create(title:"Companies of Heroes 3", genre: "Real-time strategy", release_date:"TBD", summary: "Company of Heroes 3 is an upcoming real-time strategy game developed by Relic Entertainment and published by Sega for Microsoft Windows. The game is set in the Italian and North African theaters of World War II, and features new mechanics and modes.", platform: "PC", image:"https://upload.wikimedia.org/wikipedia/en/0/06/Company_of_Heroes_3_Cover_Art.jpg", price:59.99)
game18 = Game.create(title:"Baldur's Gate III", genre: "Role-playing", release_date:"TBD", summary: "Baldur's Gate III is an upcoming role-playing video game that is being developed and published by Larian Studios. It is the third main game in the Baldur's Gate series, itself based on the Dungeons & Dragons tabletop role-playing system.", platform: "PC", image:"https://upload.wikimedia.org/wikipedia/en/d/dc/Baldur%27s_Gate_III_Logo.png", price:59.99)
game19 = Game.create(title:"Starfield", genre: "Action-adventure", release_date:"November 11, 2022", summary: "Starfield is an upcoming action role-playing video game developed by Bethesda Game Studios and published by Bethesda Softworks.[3] The game was formally announced during Bethesda's E3 Press Conference in 2018.[3] The game was described as a wholly new, next-generation experience set in an entirely new space-themed world. It will be the first new intellectual property developed by Bethesda in over twenty-five years.", platform: "PC", image:"https://upload.wikimedia.org/wikipedia/en/6/6d/Bethesda_Starfield.jpg", price:59.99)
game20 = Game.create(title:"Stranger of Paradise: Final Fantasy Origin", genre: "Action-adventure", release_date:"March 18, 2022", summary: "Stranger of Paradise: Final Fantasy Origin is an upcoming action role-playing game developed by Koei Tecmo Games and Team Ninja, and published by Square Enix in celebration of the series 35th anniversary.", platform: "PC", image:"https://upload.wikimedia.org/wikipedia/en/4/40/FF_Origin_logo.png", price:59.99)
game21 = Game.create(title:"God of War Ragnarok", genre: "Action-adventure", release_date:"TBD", summary: "God of War Ragnarök is an upcoming action-adventure hack and slash video game developed by Santa Monica Studio and will be published by Sony Interactive Entertainment. It is scheduled to be released in 2022 for the PlayStation 4 and PlayStation 5.", platform: "PS5", image:"https://upload.wikimedia.org/wikipedia/en/e/ee/God_of_War_Ragnar%C3%B6k_cover.jpg", price:59.99)
game22 = Game.create(title:"Marvel's Midnight Suns", genre: "Tactical role-playing", release_date:"TBD", summary: "Marvel's Midnight Suns is an upcoming tactical role-playing game developed by Firaxis Games in collaboration with Marvel Games. It will feature comic book characters from multiple Marvel properties, such as Midnight Sons, Avengers, X-Men, and Runaways.", platform: "PS5", image:"https://upload.wikimedia.org/wikipedia/en/4/42/Marvel%27s_Midnight_Suns.jpg", price:59.99)
game23 = Game.create(title:"Gothan Knights", genre: "Action role playing game", release_date:"TBD", summary: "Gotham Knights is an upcoming action role-playing video game developed by WB Games Montréal and published by Warner Bros. Interactive Entertainment.", platform: "PS5", image:"https://upload.wikimedia.org/wikipedia/en/a/a1/Gotham_Knights_Cover.jpg", price:59.99)
game24 = Game.create(title:"Stray", genre: "Indie gane", release_date:"TBD", summary: "Stray is an upcoming adventure game developed by BlueTwelve Studio and published by Annapurna Interactive. Formerly known as HK_Project", platform: "PS5", image:"https://upload.wikimedia.org/wikipedia/en/b/b0/Stray_game_logo.png", price:59.99)
game25 = Game.create(title:"Saints Row", genre: "Action-adventure", release_date:"August 23, 2022", summary: "Saints Row is an upcoming action-adventure video game and reboot of the Saints Row series. Developed by Volition and published by Deep Silver, it is scheduled for release on August 23, 2022", platform: "PS5", image:"https://upload.wikimedia.org/wikipedia/en/b/b5/Saints_Row_2022_Cover_Art.jpeg", price:59.99)
game26 = Game.create(title:"Forspoken", genre: "Action role-playing", release_date:"March 24, 2022", summary: "Forspoken follows the journey of Frey, a young New Yorker transported to the beautiful and cruel land of Athia. In search of a way home, Frey must use her newfound magical abilities to traverse sprawling landscapes and battle monstrous creatures.", platform: "PS5", image:"https://cdn-www.comingsoon.net/assets/uploads/2022/03/forspoken-luminous-productions-square-enix.png", price:69.99)
game27 = Game.create(title:"GhostWire: Tokyo", genre: "Action-adventure", release_date:"March 25, 2022", summary: "Ghostwire: Tokyo is an upcoming action-adventure video game developed by Tango Gameworks and published by Bethesda Softworks. The game is set to be released worldwide on March 25, 2022", platform: "PS5", image:"https://upload.wikimedia.org/wikipedia/en/d/d9/Ghostwire_Tokyo.png", price:59.99)
game28 = Game.create(title:"Tiny Tina's Wonderlands", genre: "Action role-playing", release_date:"March 25, 2022", summary: "Tiny Tina's Wonderlands is an upcoming action role-playing first-person shooter video game developed by Gearbox Software and published by 2K Games. It is a spin-off in the Borderlands series and a successor to Borderlands 2: Tiny Tina's Assault on Dragon Keep.", platform: "PS5", image:"https://upload.wikimedia.org/wikipedia/en/4/4d/Tiny_Tina_Wonderlands_cover_art.jpg", price:69.99)
game29 = Game.create(title:"Gran Turismo 7", genre: "Sim Racing", release_date:"March 04, 2022", summary: "Gran Turismo 7 is a 2022 sim racing video game developed by Polyphony Digital and published by Sony Interactive Entertainment. The game is the eighth mainline installment in the Gran Turismo series.", platform: "PS5", image:"https://upload.wikimedia.org/wikipedia/en/1/14/Gran_Turismo_7_cover_art.jpg", price:69.99)
game30 = Game.create(title:"A Memoir Blue", genre: "Sim Racing", release_date:"March, 24, 2022", summary: "A song from years ago triggers a flood of memories for champion swimmer Miriam. Embark on an evocative journey through her turbulent childhood and the complicated relationship she shared with her devoted mother.", platform: "Xbox Series X", image:"https://s3.gaming-cdn.com/images/products/9353/orig/a-memoir-blue-pc-game-steam-cover.jpg", price:59.99)
game31 = Game.create(title:"Dawn of the Monsters", genre: "Action Game", release_date:"March, 15, 2022", summary: "Dawn of the Monsters is a co-operative kaiju beat 'em up coming in early 2022. Take control of four awe-inspiring playable behemoths in order to take on the evil Nephilim—a horde of creatures that are hellbent on destroying the planet.", platform: "Xbox Series X", image:"https://images.squarespace-cdn.com/content/v1/5288d189e4b09b1867fc1547/1636049707335-GGFI68JGLI3F3FHW68SN/DoTM+Keyart+Horizontal+Approved_no_logo.png?format=1500w", price:59.99)
game32 = Game.create(title:"Century: Age of Ashes", genre: "Adventure Game", release_date:"March, 10, 2022", summary: "Century: Age of Ashes is a free-to-play multiplayer dragon battle game. Master a growing roster of classes and dragons, compete in intense arena battles and rule the skies in fast-paced aerial combats.", platform: "Xbox Series X", image:"https://static-cdn.jtvnw.net/ttv-boxart/Century:%20Age%20of%20Ashes.jpg", price:59.99)
game33 = Game.create(title:"WWE 2k22", genre: "Fighting Game", release_date:"March, 11, 2022", summary: "WWE 2K22 is a newly released professional wrestling video game developed by Visual Concepts and published by 2K Sports. It is the twenty-second overall installment of the video game series based on WWE, the ninth game under the WWE 2K banner, and the successor to 2019's WWE 2K20.", platform: "Xbox Series X", image:"https://upload.wikimedia.org/wikipedia/en/f/f8/WWE_2K22_cover.jpg", price:59.99)
game34 = Game.create(title:"Assassin's Creed Valhalla: Dawn of Ragnarok", genre: "Action Game", release_date:"March, 10, 2022", summary: "In the most ambitious expansion in franchise history, Eivor must embrace their destiny as Odin, the Norse god of Battle and Wisdom. Unleash new divine powers as you embark on a desperate quest through a breathtaking world. Complete a legendary Viking saga and save your son in the face of the gods doom.", platform: "Xbox Series X", image:"https://static.wikia.nocookie.net/assassinscreed/images/e/ec/ACV_Dawn_of_Ragnarok_cover.png/revision/latest?cb=20211213175537", price:59.99)
game35 = Game.create(title:"Redfall", genre: "Adventure Game", release_date:"September, 10, 2022", summary: "Redfall will be an open world, action-adventure first-person shooter that features both single-player and co-operative multiplayer modes. Players can choose among four playable characters — each with unique backgrounds and abilities — to fight against vampires as well as human enemies within the game.", platform: "Xbox Series X", image:"https://upload.wikimedia.org/wikipedia/en/a/ad/Redfall_cover.jpg", price:59.99)
game36 = Game.create(title:"Star Trek: Resurgence", genre: "Racing Game", release_date:"March, 31, 2022", summary: "Star Trek: Resurgence is currently set to release in the spring of 2022, as confirmed by the game's official trailer. Assuming the game's development doesn't run into any unexpected complications, gamers can expect it to be released sometime after March.", platform: "Xbox Series X", image:"https://cdn1.epicgames.com/offer/7e0d0f0b8a6e42ba962e3456c65268af/EGS_StarTrekResurgence_DramaticLabs_Demo_S2_1200x1600-b33be3b7d16a57c6ca7db5bb33849cc4", price:59.99)
game37 = Game.create(title:"The Legend of Zelda: Breath of the Wild 2", genre: "Adventure Game", release_date:"Late, 2022", summary: "An untitled sequel to the 2017 action-adventure game The Legend of Zelda: Breath of the Wild is in development by Nintendo. The sequel will be the twentieth installment of The Legend of Zelda series", platform: "Nintendo Switch", image:"https://s1.gaming-cdn.com/images/products/4860/orig/the-legend-of-zelda-breath-of-the-wild-2-switch-switch-game-nintendo-eshop-europe-cover.jpg", price:69.99)





puts "✅ Done seeding!"